const GET_CHANNEL_LIST_REQUEST = 'GET_CHANNEL_LIST_REQUEST';
const GET_CHANNEL_LIST_SUCCESS = 'GET_CHANNEL_LIST_SUCCESS';
const GET_CHANNEL_LIST_FAILURE = 'GET_CHANNEL_LIST_FAILURE';

const types = {
  GET_CHANNEL_LIST_REQUEST,
  GET_CHANNEL_LIST_SUCCESS,
  GET_CHANNEL_LIST_FAILURE,
};

export default types;
