const GET_CHANNEL_LIST_REQUEST = 'GET_CHANNEL_LIST_REQUEST';
const GET_CHANNEL_LIST_SUCCESS = 'GET_CHANNEL_LIST_SUCCESS';
const GET_CHANNEL_LIST_FAILURE = 'GET_CHANNEL_LIST_FAILURE';

const POST_CHANNEL_REQUEST = 'POST_CHANNEL_REQUEST';
const POST_CHANNEL_SUCCESS = 'POST_CHANNEL_SUCCESS';
const POST_CHANNEL_FAILURE = 'POST_CHANNEL_FAILURE';

const CONNECT_CHANNEL_REQUEST = 'CONNECT_CHANNEL_REQUEST';
const CONNECT_CHANNEL_SUCCESS = 'CONNECT_CHANNEL_SUCCESS';
const CONNECT_CHANNEL_FAILURE = 'CONNECT_CHANNEL_FAILURE';

const DISCONNECT_CHANNEL_REQUEST = 'DISCONNECT_CHANNEL_REQUEST';
const DISCONNECT_CHANNEL_SUCCESS = 'DISCONNECT_CHANNEL_SUCCESS';
const DISCONNECT_CHANNEL_FAILURE = 'DISCONNECT_CHANNEL_FAILURE';

const types = {
  GET_CHANNEL_LIST_REQUEST,
  GET_CHANNEL_LIST_SUCCESS,
  GET_CHANNEL_LIST_FAILURE,
  POST_CHANNEL_REQUEST,
  POST_CHANNEL_SUCCESS,
  POST_CHANNEL_FAILURE,
  CONNECT_CHANNEL_REQUEST,
  CONNECT_CHANNEL_SUCCESS,
  CONNECT_CHANNEL_FAILURE,
  DISCONNECT_CHANNEL_REQUEST,
  DISCONNECT_CHANNEL_SUCCESS,
  DISCONNECT_CHANNEL_FAILURE,
};

export default types;
