const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
const GET_USER_REQUEST = 'GET_USER_REQUEST';
const GET_USER_FAILURE = 'GET_USER_FAILURE';

const types = {
  GET_USER_REQUEST,
  GET_USER_SUCCESS,
  GET_USER_FAILURE,
};

export default types;
